AccountsService: Add PrefersAccentColor to users
elementary/default-settings pull request #190
Opened 2020-10-09 21:49 UTC by cassidyjames

Will fix #175. Open to feedback.

My reason for having `0` equal "No Preference" while also having blue is because it seemed the most flexible if we wanted to change how the accent color stuff worked down the line, without hardcoding the default to blue. But maybe this is overthinking it.

2020-10-09 21:56 UTC, cassidyjames commented
Currently unsure how we want to refer to the "generic" names, but mapping them to an int/enum means we can tweak them in the comment later without affecting anything code-wise—so probably best not to get too hung up on it.

2020-10-10 04:20 UTC, danrabbit requested changes
Noticed a typo. I wonder if it would be more legible to just have each value on its own line

2020-10-10 04:20 UTC, danrabbit commented on accountsservice/io.elementary.pantheon.AccountsService.xml
> +      2 = Orange, 3 = Yellow, 4 = Green, 6 = Mint, 6 = Blue, 7 = Purple,
You have a typo here with 5, 6

2020-11-18 02:07 UTC, danrabbit commented
@cassidyjames this seems reasonable to me, should this be marked ready for review?

2020-11-18 02:12 UTC, danrabbit approved these changes
:shipit:

2020-11-18 02:12 UTC, merged